config/routes.rb
Rails.application.routes.draw do
    #NL: Calls the 'resources' method and passes it a Symbol (':posts')
    #This instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post.
    resources :topics do
      #NL ins necessary to nest posts into topics
      resources :posts, except: [:index]
    end

    #NL: we use only: [] because we don't want to create any /posts/:id routes, just  posts/:post_id/comments routes.
    resources :posts, only: [] do
        #NL: We'll display comments on the posts show view, so we won't need index or new routes.
        # We also won't give users the ability to view individual comments or edit comments, removing the need for show, update, and edit routes.
        resources :comments, only: [:create, :destroy]
        resources :favorites, only: [:create, :destroy]
        #These new lines create POST routes at the URL posts/:id/up-vote and  posts/:id/down-vote.
        # The as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path and down_vote_path.
        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote
    end

    resources :users, only: [:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]

    get 'about' => 'welcome#about'

    root "welcome#index"
end

app/models/post.rb
#When we use Rails to create a Model, the new class inherits from ApplicationRecord by default
# ApplicationRecord essentially handles interaction with the database and allows us to persist data through our class
class Post < ApplicationRecord
    # In next line, 'dependent: destroy' does a cascade delete
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    # We can see how many votes have been cast on a post by calling post.votes, thanks to the has_many :votes declaration in Post.
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy

    # The default_scope will order all posts by their created_at date, in descending order
    default_scope { order('rank DESC') }
    #NL: If the user is present, we return all posts. If not, we use the Active Record joins method to retrieve all posts which belong to a public topic.
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

    validates :title, length: {minimum: 5}, presence: true
    validates :body, length: {minimum: 20}, presence: true
    validates :topic, presence: true
    validates :user, presence: true

    def up_votes
      #Here we could have written 'self.votes'
      #This fetches a collection of votes with a value of 1. We then call count on the collection to get a total of all up votes.
      votes.where(value: 1).count
    end

    def down_votes
      votes.where(value: -1).count
    end

    def points
      votes.sum(:value)
    end

    def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show
  before_action :authorize_user_update, only: [:update]
  before_action :authorize_user_create, only: [:new, :create]
  before_action :authorize_user_delete, only: [:destroy]

  def show
        @post = Post.find(params[:id])
  end

  def new
      @topic = Topic.find(params[:topic_id])
      @post = Post.new
  end

  def create
      @topic = Topic.find(params[:topic_id])
      @post = @topic.posts.build(post_params)
      @post.user = current_user

      if @post.save
          flash[:notice] = "Post was saved."
          redirect_to [@topic, @post]
      else
          flash.now[:alert] = "There was an error saving the post. Please try again"
          render :new
      end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
      @post = Post.find(params[:id])
      @post.assign_attributes(post_params)
      if @post.save
          flash[:notice] = "Post was updated."
          redirect_to [@post.topic, @post]
      else
          flash.now[:alert] = "There was an error updating the post. Please try again."
      render :edit
      end
  end

  def destroy
      @post = Post.find(params[:id])
      if @post.destroy
          flash[:notice] = "\"#{@post.title}\" was deleted successfully."
          redirect_to @post.topic
      else
          flash.now[:alert] = "There was an error deleting the post."
          render :show
      end
  end

  private

    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authorize_user_update
      post = Post.find(params[:id])
      unless current_user == post.user || current_user.admin? || current_user.moderator?
        flash[:alert] = "You are not authorized to do that!"
        redirect_to [post.topic, post]
      end
    end

    def authorize_user_create
      unless current_user.admin? || current_user.moderator? || current_user.member?
        flash[:alert] = "You are not authorized to do that!"
        redirect_to [post.topic, post]
      end
    end

    def authorize_user_delete
      post = Post.find(params[:id])
      unless current_user.admin? || current_user == post.user
        flash[:alert] = "You are not authorized to do that!"
        redirect_to [post.topic, post]
      end
    end

end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_edit?(post)
    current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
  end

  def user_is_authorized_for_delete?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

end 

app/views/posts/_form.html.erb
<!-- The underscore at the beginning of the filename lets Rails know this is a 'partials file' -->
<!-- This form uses local variables (topic and post) instead of instance variables (@topic and @post) because 'local' passes local variables -->
<%= form_for [topic, post] do |f| %>
  <!-- NL: If there are any errors, we'll display an alert and each error -->
  <% if post.errors.any? %>
    <div class="alert alert-danger">
      <!-- 'pluralize' transforms the term 'error' to 'errors' if post.error.count>= 1, preceded by the count -->
      <h4><%= pluralize(post.errors.count, "error") %>. </h4>
        <ul>
          <% post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      <% end %>
      <%= form_group_tag(post.errors[:title]) do %>
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
      <% end %>
      <%= form_group_tag(post.errors[:body]) do %>
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
      <% end %>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/_post.html.erb
<div class="media">
  <%= render partial: 'votes/voting', locals: { post: post } %>
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to post.title, topic_post_path(post.topic, post) %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %> <br>
      <%= post.comments.count %> Comments
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

    <div class="row">
        <div class="col-md-4">
            <p>Guidelines for posts</p>
            <ul>
                <li>Make sure it rhymes.</li>
                <li>Don't use the letter "A".</li>
                <li>The incessant use of hashtags will get you banned.</li>
            </ul>
        </div>
        <div class="col-md-8">
          <!-- Partials are fragments of view code, which are called from views.-->
          <!--Partials are called with the render method. Rendering a partial is like copying and pasting view code from another file. -->
          <!-- Next line searches for (and runs) a file named '_form.html.erb' with specific values set at the 'locals' block-->
          <!-- @post.topic and @post are assigned to topic and post, respectively. This means we can refer to these local variables, rather than the @post instance variable -->
          <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
        </div>

    </div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<div class="row">
    <div class="col-md-4">
        <p>Guidelines for posts</p>
        <ul>
            <li>Make sure it rhymes.</li>
            <li>Don't use the letter "A".</li>
            <li>The incessant use of hashtags will get you banned.</li>
        </ul>
    </div>
    <div class="col-md-8">
        <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
    </div>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: 'votes/voting', locals: {post: @post} %>
  <h1>
    <%= @post.title %> <br>
    <small>
      submitted <%= time_ago_in_words(@post.created_at) %> ago by <%= @post.user.name %>
    </small>
  </h1>
</div>

    <div class="row">
        <div class="col-md-8">
            <p><%= @post.body %></p>
            <div>
                <h3>Comments: </h3>
                <%= render @post.comments %>
            </div>
            <% if current_user %>
                <%= render 'comments/form', comment: Comment.new, post: @post %>
            <% end %>
        </div>
        <% if user_is_authorized_for_post?(@post) %>
          <div class="col-md-4">
              <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
              <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete this Post?"} %>
          </div>
        <% end %>

        <div class="col-md-4">
          <h3>
            <%= pluralize(@post.points, 'point') %>
            <div>
              <small>
                <%= pluralize(@post.up_votes, 'up vote') %>,
                <%= pluralize(@post.down_votes, 'down vote') %>
              </small>
            </div>
          </h3>
          <% if current_user %>
            <%= render partial: 'favorites/favorite', locals: { post: @post} %>
          <% end %>
        </div>

    </div>