config/routes.rb
Rails.application.routes.draw do
    #NL: Calls the 'resources' method and passes it a Symbol (':posts')
    #This instructs Rails to create post routes for creating, updating, viewing, and deleting instances of Post.
    resources :topics do
      #NL ins necessary to nest posts into topics
      resources :posts, except: [:index]
    end

    #NL: we use only: [] because we don't want to create any /posts/:id routes, just  posts/:post_id/comments routes.
    resources :posts, only: [] do
        #NL: We'll display comments on the posts show view, so we won't need index or new routes.
        # We also won't give users the ability to view individual comments or edit comments, removing the need for show, update, and edit routes.
        resources :comments, only: [:create, :destroy]
        resources :favorites, only: [:create, :destroy]
        #These new lines create POST routes at the URL posts/:id/up-vote and  posts/:id/down-vote.
        # The as key-value pairs at the end stipulate the method names which will be associated with these routes: up_vote_path and down_vote_path.
        post '/up-vote' => 'votes#up_vote', as: :up_vote
        post '/down-vote' => 'votes#down_vote', as: :down_vote
    end

    resources :users, only: [:new, :create, :show]

    resources :sessions, only: [:new, :create, :destroy]

    get 'about' => 'welcome#about'

    root "welcome#index"
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
end

app/models/answer.rb
class Answer < ApplicationRecord
    belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    #NL: "A comment belongs to a post" o "a post has many comments"
    belongs_to :post
    belongs_to :user

    validates :body, length: {minimum: 5}, presence: true
    validates :user, presence: true

    after_create :send_favorite_emails

    private

       def send_favorite_emails
         post.favorites.each do |favorite|
           FavoriteMailer.new_comment(favorite.user, post, self).deliver_now
         end
       end
       
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
#When we use Rails to create a Model, the new class inherits from ApplicationRecord by default
# ApplicationRecord essentially handles interaction with the database and allows us to persist data through our class
class Post < ApplicationRecord
    # In next line, 'dependent: destroy' does a cascade delete
    belongs_to :topic
    belongs_to :user
    has_many :comments, dependent: :destroy
    # We can see how many votes have been cast on a post by calling post.votes, thanks to the has_many :votes declaration in Post.
    has_many :votes, dependent: :destroy
    has_many :favorites, dependent: :destroy

    # The default_scope will order all posts by their created_at date, in descending order
    default_scope { order('rank DESC') }
    #NL: If the user is present, we return all posts. If not, we use the Active Record joins method to retrieve all posts which belong to a public topic.
    scope :visible_to, -> (user) { user ? all : joins(:topic).where('topics.public' => true) }

    validates :title, length: {minimum: 5}, presence: true
    validates :body, length: {minimum: 20}, presence: true
    validates :topic, presence: true
    validates :user, presence: true

    def up_votes
      #Here we could have written 'self.votes'
      #This fetches a collection of votes with a value of 1. We then call count on the collection to get a total of all up votes.
      votes.where(value: 1).count
    end

    def down_votes
      votes.where(value: -1).count
    end

    def points
      votes.sum(:value)
    end

    def update_rank
     age_in_days = (created_at - Time.new(1970,1,1)) / 1.day.seconds
     new_rank = points + age_in_days
     update_attribute(:rank, new_rank)
   end

end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/sponsored_post.rb
class SponsoredPost < ApplicationRecord
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, dependent: :destroy

    validates :name, length: {minimum: 5}, presence: true
    validates :description, length: {minimum: 20}, presence: true
    
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy

  before_save { self.email = email.downcase if email.present? }
  #NL is the same as: self.role = :member if self.role.nil? It says: check if self.role exists; if not, set it to ':member'
  before_save { self.role ||= :member }

  validates :name, length: { minimum: 1, maximum: 100}, presence: true

  validates :password, presence: true, length: {minimum: 6}, if: "password_digest.nil?"
  validates :password, length: {minimum: 6}, allow_blank: true

  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false},
            length: { minimum: 3, maximum: 254}

  has_secure_password

  enum role: [:member, :admin]

  def favorite_for(post)
    favorites.where(post_id: post.id).first
  end

  def avatar_url(size)
    gravatar_id = Digest::MD5::hexdigest(self.email).downcase
    "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_post

  validates :value, inclusion: { in: [-1, 1], message: "%{value} is not a valid vote."}, presence: true

private

  def update_post
    post.update_rank
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
    def user_is_authorized_for_comment?(comment)
      current_user && (current_user == comment.user || current_user.admin?)
   end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper

  def user_is_authorized_for_edit?(post)
    current_user && (current_user == post.user || current_user.admin? || current_user.moderator?)
  end

  def user_is_authorized_for_delete?(post)
    current_user && (current_user == post.user || current_user.admin?)
  end

end 

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def create_session(user)
    # 'session' is an object Rails provides to track the state of a particular user
    # There is a 1:1 relationship between session objects and user ids
    # When the user closes the app, the 'session' object is automatically destroyed
    session[:user_id] = user.id
  end

  def destroy_session(user)
    # We clear the user id on the session object by setting it to nil, which effectively destroys the user session because we can't track it via their user id any longer.
    session[:user_id] = nil
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

end

app/helpers/topics_helper.rb
module TopicsHelper

  def user_is_authorized_for_topics_cd?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_topics_u?
    current_user && (current_user.moderator? || current_user.admin?)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_has_posts_or_comments?(user)
    if user.posts.count > 0 || user.comments.count > 0
      return true
    else
      return false
    end
  end

end

app/helpers/votes_helper.rb
module VotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloccit</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
          <!-- "link_to" is a helper Ruby method that renders a valid hyperlink, corresponding to the route set at
        the second argument ("welcome_index_path"). The text to appear at HTML is the first argument ('Home')-->
        <!-- container, nav, and nav-tabs are classes provided by Bootstrap. By assigning these classes to HTML elements like <div> and <ul>, you are styling them with default Bootstrap properties and values-->
        <ul class= "nav nav-tabs">
            <li> <%= link_to "Bloccit", root_path %></li>
            <!-- Next line provides a link to topics#index -->
            <li> <%= link_to "Topics", topics_path %></li>
            <li> <%= link_to "About", about_path %></li>
            <% if current_user %>
              <li class="pull-right"><%= link_to "Sign Out", session_path(current_user), method: :delete %></li>
              <li class="pull-right"><%= image_tag current_user.avatar_url(48) %></li>
              <li class="pull-right"><%= link_to current_user.name, user_path(current_user) %></li>
            <% else %>
              <li class="pull-right"><%= link_to "Sign In", new_session_path %></li>
              <li class="pull-right"><%= link_to "Sign Up", new_user_path %></li>
            <% end %>
        </ul>
        <% if flash[:notice] %>
            <div class="alert alert-success">
                <!-- Ask Wilson: why is '&times' used in the next line? -->
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <!-- NL seems to be necessary to print the contents of flash[:notice] -->
                <%= flash[:notice] %>
            </div>
        <% elsif flash[:alert] %>
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <%= flash[:alert] %>
            </div>
        <%end %>

        <%= yield %>
    </div>

  </body>
</html>